name: CI
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        with:
          branches: |
            [
              "main",
              { "name": "beta", "prerelease": true },
              { "name": "alpha", "prerelease": true }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          repository_url: https://github.com/AkiVonAkira/com.akira.tools.git
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
