name: CI
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        with:
          branches: |
            [
              "main",
              { "name": "beta", "prerelease": true },
              { "name": "alpha", "prerelease": true }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
